### ISSUE TITLE
Text overflows editor - last characters cut off

### ISSUE THREAD

**Issue by stebiger** [coopermaruyama/apathy-theme#17]
When writing to the right end of the editor the last characters are cut off and you can not scroll further to see them:

![image](https://cloud.githubusercontent.com/assets/8200750/8746503/3119615c-2c8a-11e5-9656-2f04afb74f2e.png)

Other syntax theme:

![image](https://cloud.githubusercontent.com/assets/8200750/8746511/3bf9440c-2c8a-11e5-8070-36664ebfe59e.png)

**Comment by czxtm** [comment]
Oh wow, thanks for catching that, that's a huge bug. I'm on it.

**Comment by czxtm** [comment]
Please let me know if this fixed it?

**Comment by stebiger** [comment]
Yeah it fixes the problem thank you.
But now the Source Code Pro font is bold after Update and I have not (yet) found where this setting is hidden?

**Comment by czxtm** [comment]
Sorry, this will be documented soon. Put this in your stylesheet ('open your stylesheet' in the command palette):

``` less
atom-text-editor::shadow .source {
  -webkit-text-stroke-width: 0.03em; // This is the default, you probably want something like 0.02em;
  // Alternatively you can use font weight instead. 
  font-weight: 400; // you can use any of the following here: 200, 300, 400, 700, 800, 900;
}
```

Keep in mind that the above will not affect certain scopes which override the setting above. In that case you can pull up the developer tools in order to find the proper CSS class to use.
