### ISSUE TITLE
Change Font && Make blinking Cursor in Vim-Mode

### ISSUE THREAD

**Issue by ghost** [coopermaruyama/apathy-theme#18]
Hello, I really like this theme but I can't for the life of me get it to change my font back. I have already tried to add it to my custom stylesheet, as seen on the screenshot. 

Also, I am using vim-mode, is there anyway I can get the cursor to blink on and off? I had it set up before like that but it's not working anymore. Thanks. 
![screenshot-window-2015-07-24-172614](https://cloud.githubusercontent.com/assets/3500392/8887047/61cda318-3229-11e5-9601-d4877ccc415d.png)

**Comment by czxtm** [comment]
Hey, thanks for making this issue and I'm very glad you like the theme :smile: 

In order to override the theme font, you need to set it in your user stylesheet using the following css:

``` css
atom-text-editor::shadow .source {
  font-family: 'CamingoCode' !important;
  // might want to play with this too as we change this setting from default
  -webkit-text-stroke-width: 0.04em; // this is the value we use, default is 0.
}
```

As to your vim issue, I am looking into that as we speak.

**Comment by czxtm** [comment]
I'm not sure exactly what your customization to vim-mode does, but I was able to get the initial cursor (th block one) to blink using this code:

``` less
atom-text-editor.vim-mode.is-focused {
  &.command-mode,
  &.operator-pending-mode,
  &.normal-mode,
  &.visual-mode {
    &::shadow .cursors.blink-off .cursor {
      opacity: 0;
    }
  }
}
```
