### ISSUE TITLE
The non-active pan brightness

### ISSUE THREAD

**Issue by ghost** [coopermaruyama/apathy-theme#25]
It would be nice, if there would be an option in the menu for adjusting that

**Comment by czxtm** [comment]
Hmm I'll leave this open to see if others feel the same. For now you can add the following to your user stylesheet ("Open your Stylesheet" in command palette):

``` css
atom-pane:not(.active) atom-text-editor::shadow .source {
    // -webkit-filter: brightness(60%) opacity(0.8) !important; // default setting
    -webkit-filter: brightness(80%) opacity(0.8) !important; // brighter inactive panes
}
```
